name: Ruff Lint

on: [push]

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
